name: gpdi_mobile
description: "Base Project Aplikasi Jemaat GPdI Sibulele"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.1.2
  dio: ^5.4.3
  flutter_secure_storage: ^9.2.1
  go_router: ^14.0.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  intl: ^0.20.2
  image_picker: ^1.0.7
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  path_provider_foundation: 2.5.1

flutter:
  uses-material-design: true
  assets:
    - web/favicon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "web/favicon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "web/favicon.png"
  # Properti di bawah ini membantu memastikan icon tidak terdistorsi di beberapa versi Android
  web:
    generate: true
    image_path: "web/favicon.png"
    backgroundColor: "#FFFFFF"
    themeColor: "#FFFFFF"
